language: node_js
node_js:
- 0.1
- 0.12
before_install:
- npm install -g phantomjs
env:
  global:
  - secure: FhRSjEy+E8gHjNnf2DAX5cWCrvjxRh6vlWIIAD+UP8LbtVHyUPUvFVaWfr4c2SgtsRWz1MUmBN1g5Y29FDZKlIjc7hjKkJi/Y2qLR25+h4peptD65RB2bgnlvZ4YWgoFGC6ADGdLm+QQhI10dsL+R3F0OdWyWOmd8oMTbba8Ezc=
  - secure: c0839qVL/zjchXba/FFIziKnlXUEGH/OOizPQ7lWMZdOeqirizbgZeYV2f3rgRhblUO+MRP7j8BFXfkiKcsDJZJxaDE4/HvhB8tEaPTumAAbhbafHjm1MBL/mbZlIqSQXnsFk4BElDTwWF+W5PUtKTBYJKa3/F8RhCPsT8za470=
addons:
  sauce_connect: true
