language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g phantomjs
env:
  global:
    - secure: aAJzCSZI3uqmLaxq94+gsANCNe0qMPksZhJ1xJ30x/kgBY4jQw8uiTx22Z7AU4LsgT1zEYar0A6NAD/cegqJdyV0u9BmSeZV3p1o/rqiL2eXEQPHT6mXp+51qUeo2uuS6p3Y2WTovIoH0LO8RCmxZTvhQoLu24WxFj6NLU94F0s=
    - secure: FCaBEkuIEm5rgW+FoAl8rvCm6Yx1hqFnVJRyju70hMh0DbwhFJCOHIJDkHSI22ZzZg9THn8Vsp0hDNWZLDpQjjtp3OMzhAA/0VPM+oELqms6TWHOljOjO8bg/1C6A4ui0VDXiGJGfAUD0xdQDM4cSUM5kmyHApIdQAVtXdWaJ84=
