language: node_js
node_js:
- 0.1
- 0.12
before_install:
- npm install -g phantomjs
env:
  global:
  - secure: sqmvPoHV5nK5eGc97FChcX2CWhM+sbM8rqHOyEkhFuhE7hKtDIZV1c38YQqOEPzjH3qW6iQm8AEbWoUc2vdJNDTRYfdiIG02lbtEuHLI4s+YvEo+7ikEh8WKKtMMvrLLctYApa9opFZd5YTxHe4NToYNJaPkMmjshHtWkQQr9PQ=
  - secure: 0qXOcKRiQdkH1eDnxrWFo5zslFqRaNlcyJ4tBR+bCTq+Cku55juIFCEbGqc//BafS16TZn9hAGHKZVvM1IF3GJShZVN3ESKrRnGVD2LvJMDgaRszYtNXs0c2oKcgAqDR46tCPyTc3cVrsM8fm8+sgTzd56oggXbJPrekWBZsNBo=
addons:
  sauce_connect: true
